{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " Python Version:  3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]\n",
      "    Python Path:  C:\\ProgramData\\Anaconda3\\envs\\py36\n"
     ]
    }
   ],
   "source": [
    "# My Standard Spark Session!\n",
    "\n",
    "# Python libraries:\n",
    "import os\n",
    "import sys\n",
    "import re\n",
    "import math\n",
    "import random\n",
    "from dateutil import parser\n",
    "# import datetime\n",
    "from datetime import datetime\n",
    "from datetime import date\n",
    "import builtins\n",
    "import json\n",
    "import functools\n",
    "import operator\n",
    "from itertools import product\n",
    "\n",
    "\n",
    "print(\"%16s  %s\" % (\"Python Version:\",sys.version))\n",
    "print(\"%16s  %s\" % (\"Python Path:\",os.path.dirname(sys.executable)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Numpy & Pandas!\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "pd.options.display.float_format = '{:20,.2f}'.format\n",
    "pd.options.display.max_columns = None\n",
    "\n",
    "# Spark!\n",
    "from pyspark import SparkContext\n",
    "from pyspark.sql.functions import *\n",
    "from pyspark.sql.types import *\n",
    "from pyspark.sql.window import *\n",
    "from pyspark.sql import SparkSession, Row\n",
    "\n",
    "\n",
    "spark = SparkSession.builder.appName(\"myapp42\").getOrCreate()\n",
    "\n",
    "#     spark = SparkSession.builder.master(\"yarn\")\\\n",
    "#     .config(\"spark.executor.instances\", \"32\")\\\n",
    "#     .config(\"spark.executor.cores\", \"4\")\\\n",
    "#     .config(\"spark.executor.memory\", \"4G\")\\\n",
    "#     .config(\"spark.driver.memory\", \"4G\")\\\n",
    "#     .config(\"spark.executor.memoryOverhead\",\"4G\")\\\n",
    "#     .config(\"spark.yarn.queue\",\"Medium\")\\\n",
    "#     .appName(\"myapp\")\\\n",
    "#     .getOrCreate()\n",
    "\n",
    "sc = spark.sparkContext\n",
    "spark.conf.set(\"spark.sql.sources.partitionColumnTypeInference.enabled\", \"false\")\n",
    "spark.conf.set(\"spark.debug.maxToStringFields\",\"true\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n",
      " My Python Libs:  C:\\Users\\MerzDal/.myconfigs\n",
      "   My Spark Dir:  C:\\Users\\MerzDal/spark2_dfanalysis\n",
      "   My Spark Ctx:  <pyspark.sql.session.SparkSession object at 0x00000246EE894FD0>\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "# The autoreload extension is already loaded. To reload it, use:\n",
    "#  %reload_ext autoreload\n",
    "\n",
    "\n",
    "# mylib:\n",
    "my_library = os.path.expanduser('~/.myconfigs')\n",
    "my_spark = os.path.expanduser('~/spark2_dfanalysis')\n",
    "sys.path.append(my_library)\n",
    "sys.path.append(my_spark)\n",
    "\n",
    "\n",
    "from shared.app_context import *\n",
    "from builder.DataFrameBuild import *\n",
    "\n",
    "ctx = ApplicationContext(\"Dev-Job\")\n",
    "\n",
    "DFB = DataFrameBuild(ctx.spark)\n",
    "\n",
    "print(\"%16s  %s\" % (\"My Python Libs:\",my_library))\n",
    "print(\"%16s  %s\" % (\"My Spark Dir:\",my_spark))\n",
    "print(\"%16s  %s\" % (\"My Spark Ctx:\",ctx.spark))\n",
    "# print(ctx.spark)\n",
    "# print(os.listdir(my_spark))\n",
    "# print(sys.path)\n",
    "# print(\"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Standard lists:\n",
    "lst_dates = sorted([str(x) for x in range(1980,2021,1)],reverse=True)\n",
    "lst_6 = list([int(x) for x in np.linspace(0,5,6)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dates:\n",
      " ['2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995', '1994', '1993', '1992', '1991', '1990', '1989', '1988', '1987', '1986', '1985', '1984', '1983', '1982', '1981', '1980']\n",
      "\n",
      "lst_6:\n",
      " [0, 1, 2, 3, 4, 5]\n"
     ]
    }
   ],
   "source": [
    "print(\"Dates:\\n\",lst_dates)\n",
    "print(\"\\nlst_6:\\n\",lst_6)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Input:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "arr = [[1, 1, 1, 0, 0, 0],\n",
    "[0, 1, 0, 0, 0, 0],\n",
    "[1, 1, 1, 0, 0, 0],\n",
    "[0, 0, 2, 4, 4, 0],\n",
    "[0, 0, 0, 2, 0, 0],\n",
    "[0, 0, 1, 2, 4, 0]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[1, 1, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 1, 1, 0, 0, 0], [0, 0, 2, 4, 4, 0], [0, 0, 0, 2, 0, 0], [0, 0, 1, 2, 4, 0]]\n",
      "RxC:  6 6\n",
      "0 0\n",
      "top:\n",
      " [1, 1, 1]\n",
      "mid: \n",
      " 1\n",
      "bot: \n",
      " [1, 1, 1]\n",
      "0 1\n",
      "top:\n",
      " [1, 1, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [1, 1, 0]\n",
      "0 2\n",
      "top:\n",
      " [1, 0, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [1, 0, 0]\n",
      "0 3\n",
      "top:\n",
      " [0, 0, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [0, 0, 0]\n",
      "\n",
      "\n",
      "\n",
      "1 0\n",
      "top:\n",
      " [0, 1, 0]\n",
      "mid: \n",
      " 1\n",
      "bot: \n",
      " [0, 0, 2]\n",
      "1 1\n",
      "top:\n",
      " [1, 0, 0]\n",
      "mid: \n",
      " 1\n",
      "bot: \n",
      " [0, 2, 4]\n",
      "1 2\n",
      "top:\n",
      " [0, 0, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [2, 4, 4]\n",
      "1 3\n",
      "top:\n",
      " [0, 0, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [4, 4, 0]\n",
      "\n",
      "\n",
      "\n",
      "2 0\n",
      "top:\n",
      " [1, 1, 1]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [0, 0, 0]\n",
      "2 1\n",
      "top:\n",
      " [1, 1, 0]\n",
      "mid: \n",
      " 2\n",
      "bot: \n",
      " [0, 0, 2]\n",
      "2 2\n",
      "top:\n",
      " [1, 0, 0]\n",
      "mid: \n",
      " 4\n",
      "bot: \n",
      " [0, 2, 0]\n",
      "2 3\n",
      "top:\n",
      " [0, 0, 0]\n",
      "mid: \n",
      " 4\n",
      "bot: \n",
      " [2, 0, 0]\n",
      "\n",
      "\n",
      "\n",
      "3 0\n",
      "top:\n",
      " [0, 0, 2]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [0, 0, 1]\n",
      "3 1\n",
      "top:\n",
      " [0, 2, 4]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [0, 1, 2]\n",
      "3 2\n",
      "top:\n",
      " [2, 4, 4]\n",
      "mid: \n",
      " 2\n",
      "bot: \n",
      " [1, 2, 4]\n",
      "3 3\n",
      "top:\n",
      " [4, 4, 0]\n",
      "mid: \n",
      " 0\n",
      "bot: \n",
      " [2, 4, 0]\n",
      "\n",
      "\n",
      "\n",
      "[7, 4, 2, 0, 4, 8, 10, 8, 3, 6, 7, 6, 3, 9, 19, 14]\n",
      "19\n",
      "19\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "#     fptr = open(os.environ['OUTPUT_PATH'], 'w')\n",
    "\n",
    "#     arr = []\n",
    "\n",
    "#     for _ in range(6):\n",
    "#         arr.append(list(map(int, input().rstrip().split())))\n",
    "\n",
    "#     result = myfunc(arr)\n",
    "\n",
    "#     fptr.write(str(result) + '\\n')\n",
    "\n",
    "#     fptr.close()\n",
    "\n",
    "    # max\n",
    "    result = myfunc(arr)\n",
    "    print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Complete the function below.\n",
    "\n",
    "def get_top():\n",
    "    pass\n",
    "\n",
    "\n",
    "def myfunc(arr):\n",
    "    print(arr)\n",
    "    \n",
    "    # get hourglass\n",
    "    print(\"RxC: \", len(arr), len(arr[0]))\n",
    "    \n",
    "    hg = []\n",
    "    \n",
    "    for i in range(len(arr)-2):\n",
    "        for j in range(len(arr)-2):\n",
    "            print(i,j)\n",
    "            \n",
    "            top = arr[i][j:j+3]\n",
    "            mid = arr[i+1][j+1]\n",
    "            bot = arr[i+2][j:j+3]\n",
    "            \n",
    "            print(\"top:\\n\", top)\n",
    "            print(\"mid: \\n\", mid)\n",
    "            print(\"bot: \\n\", bot)\n",
    "                  \n",
    "            top_sum = 0\n",
    "            for x in top:\n",
    "                top_sum += x\n",
    "                \n",
    "            bot_sum = 0\n",
    "            for x in bot:\n",
    "                bot_sum += x\n",
    "                \n",
    "            total = top_sum + mid + bot_sum\n",
    "            hg.append(total)\n",
    "            \n",
    "            #print(top_sum)\n",
    "        \n",
    "        print(\"\\n\\n\")\n",
    "      \n",
    "    #print(hg)\n",
    "    \n",
    "    x = hg[0]\n",
    "    for y in hg:\n",
    "        if y > x:\n",
    "            x = y\n",
    "    print(x)\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
